name: Viswanathan Research Group @CMU
url: https://eeg.engin.umich.edu

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: pi
    name: PI
  - key: postdoc
    name: Postdoctoral Researchers
#  - key: staff
#    name: Research Staff
  - key: phd
    name: Doctoral Students
  - key: masters
    name: Master's Students
  - key: ugrad
    name: Undergraduate Students
  - key: alumni-masters
    name: Master's Alumni
  - key: alumni-phd
    name: PhD Alumni
  - key: alumni-postdoc
    name: Postdoc Alumni
  - key: alumni-ugrad
    name: Former Undergraduate Students

# Number of news stories on the front page.
front_page_news: 8

# Google Analytics
google_analytics: G-T2THDG38MZ

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /index.html
  - title: People
    link: /index.html#people
  - title: Research
    link: /index.html#research
  - title: News
    link: /index.html#news
  - title: Publications
    link: /publications.html
  - title: Patents
    link: /patents.html
  - title: Software
    link: /software.html
  - title: Sponsors
    link: /sponsors.html
#  - title: Code
#    link: /code.html
